---
title: '7. シミュレーションを利用して大数の法則を理解する'
subtitle: ''
author: 'honocat'
date: '`r Sys.Date()`'
execute:
  echo: true
  warning: false
  message: true
format:
  pdf:
    fig-width: 5
    fig-height: 3
  html:
    fig-width: 5
    fig-height: 3
pdf-engine: lualatex
documentclass: ltjsarticle
lang: ja
---

```{r global_option}
#| include: false

if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = 'cairo_pdf')
}
```

```{r}
#| echo: false
#| message:  false

library(tidyverse)
my_font <- 'HiraginoSans-W3'
theme_set(theme_gray(base_size = 9,
                     base_family = my_font))
```

## 大数の法則（Law of Large Numbers; LLN）

「公正な」コインを使って、大数の法則のシミュレーションを行う。

1. 表が出れば1
1. 裏が出れば0

コイン投げの回数が少ないと、表が出る比率は真の比率である0.5に近くなるとは限らない。しかし、大数の法則によると、コインを投げる回数を十分大きくすると、表の比率は0.5に近づくはずである。確かめてみよう。

```{r}
coin <- c('表', '裏')
n_flips <- 500 # コインを投げる回数
ratio_1 <- rep(NA, n_flips) # 結果の記録
```

`n_flip`回コイン投げを行い、それぞれのコイン投げが終わった時点での表の比率を計算する。

```{r}
coins_1 <- sample(coin, size = n_flips, replace = TRUE)
for (i in 1 : n_flips) {
  n_head <- sum(coins_1[1 : i] == '表') # i回目までに何回表が出たか
  ratio_1[i] <- n_head / i              # i回目までの表の比率を計算
}
```

結果を図示する。

```{r}
df2 <- tibble(N = 1 : n_flips,
              ratio_1 = ratio_1)
p1 <- ggplot(df2, aes(x = N, y = ratio_1)) +
  geom_hline(yintercept = 0.5,
             linetype   = 'dashed') +
  geom_line(color = 'dodgerblue') +
  labs(x = '試行回数',
       y = '表の割合')
plot(p1)
```

比率が少しずつ0.5に近づいていくことがわかる。

もう一度。

```{r}
ratio_2 <- rep(NA, n_flips)
coins_2 <- sample(coin, size = n_flips, replace = TRUE)
for (i in 1 : n_flips) {
  n_head <- sum(coins_2[1 : i] == '表')
  ratio_2[i] <- n_head / i
}
df2$ratio_2 <- ratio_2
p2 <- ggplot(df2, aes(x = N, y = ratio_2)) +
  geom_hline(yintercept = 0.5,
             linetype   = 'dashed') +
  geom_line(color = 'dodgerblue') +
  labs(x = '試行回数',
       y = '表の割合')
plot(p2)
```

もう一度。

```{r}
ratio_3 <- rep(NA, n_flips)
coins_3 <- sample(coin, size = n_flips, replace = TRUE)
for (i in 1 : n_flips) {
  n_head <- sum(coins_3[1 : i] == '表')
  ratio_3[i] <- n_head / i
}
df2$ratio_3 <- ratio_3
p3 <- ggplot(df2, aes(x = N, y = ratio_3)) +
  geom_hline(yintercept = 0.5,
             linetype   = 'dashed') +
  geom_line(color = 'dodgerblue') +
  labs(x = '試行回数',
       y = '表の割合')
plot(p3)
```

シミュレーションを実行するたびに、異なる軌跡を描きながら、比率が0.5に近づいていく様子が見て取れる。
